CREATE TABLE `inv_materialmovement_document_data_1` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `created_on` datetime DEFAULT NULL,
  `created_by` int(11) DEFAULT NULL,
  `private` int(11) DEFAULT '0',
  `active` tinyint(4) DEFAULT '1',
  `f_mm_document` varchar(10) COLLATE utf8_unicode_ci DEFAULT NULL,
  `f_reversal_document` varchar(10) COLLATE utf8_unicode_ci DEFAULT NULL,
  `f_movement_type` varchar(3) COLLATE utf8_unicode_ci DEFAULT NULL,
  `f_material_no_` int(11) DEFAULT NULL,
  `f_description_of_material` varchar(132) COLLATE utf8_unicode_ci DEFAULT NULL,
  `f_qty` varchar(16) COLLATE utf8_unicode_ci DEFAULT NULL,
  `f_asn_no_` varchar(10) COLLATE utf8_unicode_ci DEFAULT NULL,
  `f_asn_item_no_` varchar(4) COLLATE utf8_unicode_ci DEFAULT NULL,
  `f_po_no_` varchar(15) COLLATE utf8_unicode_ci DEFAULT NULL,
  `f_po_item_no_` varchar(4) COLLATE utf8_unicode_ci DEFAULT NULL,
  `f_storage_location` varchar(8) COLLATE utf8_unicode_ci DEFAULT NULL,
  `f_company` int(11) DEFAULT NULL,
  `f_vendor` int(11) DEFAULT NULL,
  `f_creater` varchar(18) COLLATE utf8_unicode_ci DEFAULT NULL,
  `f_post_date` date DEFAULT NULL,
  `f_remark` text COLLATE utf8_unicode_ci,
  `f_reversaled_document` varchar(10) COLLATE utf8_unicode_ci DEFAULT NULL,
  `f_oun` varchar(3) COLLATE utf8_unicode_ci DEFAULT NULL,
  `f_gr_excute` varchar(10) COLLATE utf8_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci