CREATE TABLE `srm_invoice_item_data_1` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `created_on` datetime DEFAULT NULL,
  `created_by` int(11) DEFAULT NULL,
  `private` int(11) DEFAULT '0',
  `active` tinyint(4) DEFAULT '1',
  `f_item_no_` varchar(4) COLLATE utf8_unicode_ci DEFAULT NULL,
  `f_invoice_no_` varchar(10) COLLATE utf8_unicode_ci DEFAULT NULL,
  `f_po_no_` varchar(15) COLLATE utf8_unicode_ci DEFAULT NULL,
  `f_po_item` varchar(10) COLLATE utf8_unicode_ci DEFAULT NULL,
  `f_material_no_` varchar(20) COLLATE utf8_unicode_ci DEFAULT NULL,
  `f_description_of_material` varchar(40) COLLATE utf8_unicode_ci DEFAULT NULL,
  `f_quantity` int(11) DEFAULT NULL,
  `f_unit` varchar(128) COLLATE utf8_unicode_ci DEFAULT NULL,
  `f_price` varchar(128) COLLATE utf8_unicode_ci DEFAULT NULL,
  `f_po_item_remark` varchar(40) COLLATE utf8_unicode_ci DEFAULT NULL,
  `f_invoice_remark` varchar(256) COLLATE utf8_unicode_ci DEFAULT NULL,
  `f_remark_indicator` varchar(10) COLLATE utf8_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci