CREATE TABLE `srm_quotation_data_1` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `created_on` datetime DEFAULT NULL,
  `created_by` int(11) DEFAULT NULL,
  `private` int(11) DEFAULT '0',
  `active` tinyint(4) DEFAULT '1',
  `f_vq_no_` varchar(10) COLLATE utf8_unicode_ci DEFAULT NULL,
  `f_rfq_no_` varchar(10) COLLATE utf8_unicode_ci DEFAULT NULL,
  `f_title` varchar(132) COLLATE utf8_unicode_ci DEFAULT NULL,
  `f_rfq_type` varchar(128) COLLATE utf8_unicode_ci DEFAULT NULL,
  `f_rfq_date` date DEFAULT NULL,
  `f_quotation_deadline` date DEFAULT NULL,
  `f_quotation_date` date DEFAULT NULL,
  `f_buyer` int(11) DEFAULT NULL,
  `f_company` int(11) DEFAULT NULL,
  `f_vendor` int(11) DEFAULT NULL,
  `f_total_price` varchar(128) COLLATE utf8_unicode_ci DEFAULT NULL,
  `f_quotation_progress` varchar(2) COLLATE utf8_unicode_ci DEFAULT NULL,
  `f_quotation_person` int(11) DEFAULT NULL,
  `f_attachment` tinyint(4) DEFAULT NULL,
  `f_remark` varchar(256) COLLATE utf8_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci