CREATE TABLE `srm_po_datefeedback_data_1` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `created_on` datetime DEFAULT NULL,
  `created_by` int(11) DEFAULT NULL,
  `private` int(11) DEFAULT '0',
  `active` tinyint(4) DEFAULT '1',
  `f_po_df_no_` varchar(10) COLLATE utf8_unicode_ci DEFAULT NULL,
  `f_po_no_` varchar(16) COLLATE utf8_unicode_ci DEFAULT NULL,
  `f_item_no_` varchar(16) COLLATE utf8_unicode_ci DEFAULT NULL,
  `f_material_no_` varchar(16) COLLATE utf8_unicode_ci DEFAULT NULL,
  `f_description_of_material` varchar(16) COLLATE utf8_unicode_ci DEFAULT NULL,
  `f_required_quantity` varchar(16) COLLATE utf8_unicode_ci DEFAULT NULL,
  `f_oun` varchar(16) COLLATE utf8_unicode_ci DEFAULT NULL,
  `f_process_type` varchar(128) COLLATE utf8_unicode_ci DEFAULT NULL,
  `f_delivery_date` date DEFAULT NULL,
  `f_open_quantity` varchar(64) COLLATE utf8_unicode_ci DEFAULT NULL,
  `f_company` varchar(16) COLLATE utf8_unicode_ci DEFAULT NULL,
  `f_vendor` varchar(16) COLLATE utf8_unicode_ci DEFAULT NULL,
  `f_feedback_process` varchar(128) COLLATE utf8_unicode_ci DEFAULT NULL,
  `f_item_quantity` varchar(10) COLLATE utf8_unicode_ci DEFAULT NULL,
  `f_submitted_date` date DEFAULT NULL,
  `f_parentid` varchar(16) COLLATE utf8_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci