CREATE TABLE `srm_po_item_data_1` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `created_on` datetime DEFAULT NULL,
  `created_by` int(11) DEFAULT NULL,
  `private` int(11) DEFAULT '0',
  `active` tinyint(4) DEFAULT '1',
  `f_item_no_` varchar(4) COLLATE utf8_unicode_ci DEFAULT NULL,
  `f_po_no_` varchar(16) COLLATE utf8_unicode_ci DEFAULT NULL,
  `f_item_category` varchar(128) COLLATE utf8_unicode_ci DEFAULT NULL,
  `f_object_item_no_` int(11) DEFAULT NULL,
  `f_delivery_schedule` tinyint(4) DEFAULT NULL,
  `f_no_material` tinyint(4) DEFAULT NULL,
  `f_material_no_` int(11) DEFAULT NULL,
  `f_description_of_material` varchar(80) COLLATE utf8_unicode_ci DEFAULT NULL,
  `f_source_list` tinyint(4) DEFAULT NULL,
  `f_require_delivery_date` date DEFAULT NULL,
  `f_po_quantity` int(11) DEFAULT NULL,
  `f_oun` varchar(128) COLLATE utf8_unicode_ci DEFAULT NULL,
  `f_net_price` varchar(128) COLLATE utf8_unicode_ci DEFAULT NULL,
  `f_price_unit` int(11) DEFAULT NULL,
  `f_opu` varchar(128) COLLATE utf8_unicode_ci DEFAULT NULL,
  `f_sub_summary` varchar(128) COLLATE utf8_unicode_ci DEFAULT NULL,
  `f_plant` varchar(40) COLLATE utf8_unicode_ci DEFAULT NULL,
  `f_storage_location` varchar(40) COLLATE utf8_unicode_ci DEFAULT NULL,
  `f_open_quantity` varchar(16) COLLATE utf8_unicode_ci DEFAULT NULL,
  `f_available_quantity` varchar(16) COLLATE utf8_unicode_ci DEFAULT NULL,
  `f_remark` text COLLATE utf8_unicode_ci,
  `f_poid` varchar(15) COLLATE utf8_unicode_ci DEFAULT NULL,
  `f_oun1` varchar(15) COLLATE utf8_unicode_ci DEFAULT NULL,
  `f_opu1` varchar(15) COLLATE utf8_unicode_ci DEFAULT NULL,
  `f_promise_times` varchar(15) COLLATE utf8_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci