CREATE TABLE `srm_purchaseplanning_data_1` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `created_on` datetime DEFAULT NULL,
  `created_by` int(11) DEFAULT NULL,
  `private` int(11) DEFAULT '0',
  `active` tinyint(4) DEFAULT '1',
  `f_version` int(11) DEFAULT NULL,
  `f_company` int(11) DEFAULT NULL,
  `f_plant` varchar(64) COLLATE utf8_unicode_ci DEFAULT NULL,
  `f_purchase_planning_type` varchar(128) COLLATE utf8_unicode_ci DEFAULT NULL,
  `f_year` int(11) DEFAULT NULL,
  `f_month` int(11) DEFAULT NULL,
  `f_no_material` tinyint(4) DEFAULT NULL,
  `f_material_no_` int(11) DEFAULT NULL,
  `f_description_of_material` varchar(80) COLLATE utf8_unicode_ci DEFAULT NULL,
  `f_source_list` tinyint(4) DEFAULT NULL,
  `f_quantity` int(11) DEFAULT NULL,
  `f_unit` varchar(128) COLLATE utf8_unicode_ci DEFAULT NULL,
  `f_delivery_date` date DEFAULT NULL,
  `f_buyer` int(11) DEFAULT NULL,
  `f_private` tinyint(4) DEFAULT NULL,
  `f_block_indicator` tinyint(4) DEFAULT NULL,
  `f_remark` text COLLATE utf8_unicode_ci,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci