CREATE TABLE `srm_po_promise_data_1` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `created_on` datetime DEFAULT NULL,
  `created_by` int(11) DEFAULT NULL,
  `private` int(11) DEFAULT '0',
  `active` tinyint(4) DEFAULT '1',
  `f_po_promise_no_` varchar(10) COLLATE utf8_unicode_ci DEFAULT NULL,
  `f_po_no_` varchar(16) COLLATE utf8_unicode_ci DEFAULT NULL,
  `f_item_no_` varchar(16) COLLATE utf8_unicode_ci DEFAULT NULL,
  `f_itembatch_no_` varchar(16) COLLATE utf8_unicode_ci DEFAULT NULL,
  `f_material_no_` varchar(16) COLLATE utf8_unicode_ci DEFAULT NULL,
  `f_description_of_material` varchar(16) COLLATE utf8_unicode_ci DEFAULT NULL,
  `f_quantity` varchar(16) COLLATE utf8_unicode_ci DEFAULT NULL,
  `f_oun` varchar(16) COLLATE utf8_unicode_ci DEFAULT NULL,
  `f_require_delivery_date` varchar(20) COLLATE utf8_unicode_ci DEFAULT NULL,
  `f_commitment_to_delivery` date DEFAULT NULL,
  `f_deviation_days` varchar(5) COLLATE utf8_unicode_ci DEFAULT NULL,
  `f_company` varchar(16) COLLATE utf8_unicode_ci DEFAULT NULL,
  `f_vendor` varchar(16) COLLATE utf8_unicode_ci DEFAULT NULL,
  `f_read_time` varchar(20) COLLATE utf8_unicode_ci DEFAULT NULL,
  `f_promise_no_` varchar(16) COLLATE utf8_unicode_ci DEFAULT NULL,
  `f_edit_by` int(11) DEFAULT NULL,
  `f_status` varchar(128) COLLATE utf8_unicode_ci DEFAULT NULL,
  `f_replaced` varchar(1) COLLATE utf8_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci