CREATE TABLE `srm_materialmanage_data_1` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `created_on` datetime DEFAULT NULL,
  `created_by` int(11) DEFAULT NULL,
  `private` int(11) DEFAULT '0',
  `active` tinyint(4) DEFAULT '1',
  `f_material_no_` varchar(20) COLLATE utf8_unicode_ci DEFAULT NULL,
  `f_description` varchar(132) COLLATE utf8_unicode_ci DEFAULT NULL,
  `f_material_type` varchar(128) COLLATE utf8_unicode_ci DEFAULT NULL,
  `f_additional_no_` varchar(40) COLLATE utf8_unicode_ci DEFAULT NULL,
  `f_basic_units` varchar(128) COLLATE utf8_unicode_ci DEFAULT NULL,
  `f_old_material_no_` varchar(18) COLLATE utf8_unicode_ci DEFAULT NULL,
  `f_gross_weight` double DEFAULT NULL,
  `f_net_weight` double DEFAULT NULL,
  `f_unit_of_weight` varchar(128) COLLATE utf8_unicode_ci DEFAULT NULL,
  `f_volume_size` varchar(20) COLLATE utf8_unicode_ci DEFAULT NULL,
  `f_volume_unit` varchar(128) COLLATE utf8_unicode_ci DEFAULT NULL,
  `f_material_group` int(11) DEFAULT NULL,
  `f_packing` varchar(128) COLLATE utf8_unicode_ci DEFAULT NULL,
  `f_drawing` varchar(126) COLLATE utf8_unicode_ci DEFAULT NULL,
  `f_block_indicator` tinyint(4) DEFAULT NULL,
  `f_quote_indicator` varchar(2) COLLATE utf8_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci