CREATE TABLE `srm_advancedshippingnote_item_data_1` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `created_on` datetime DEFAULT NULL,
  `created_by` int(11) DEFAULT NULL,
  `private` int(11) DEFAULT '0',
  `active` tinyint(4) DEFAULT '1',
  `f_asn_no_` varchar(10) COLLATE utf8_unicode_ci DEFAULT NULL,
  `f_item_no_` varchar(10) COLLATE utf8_unicode_ci DEFAULT NULL,
  `f_material_no_` varchar(18) COLLATE utf8_unicode_ci DEFAULT NULL,
  `f_description_of_material` varchar(132) COLLATE utf8_unicode_ci DEFAULT NULL,
  `f_po_item` varchar(40) COLLATE utf8_unicode_ci DEFAULT NULL,
  `f_po_quantity` varchar(20) COLLATE utf8_unicode_ci DEFAULT NULL,
  `f_open_po_quantity` varchar(20) COLLATE utf8_unicode_ci DEFAULT NULL,
  `f_available_po_quantity` varchar(20) COLLATE utf8_unicode_ci DEFAULT NULL,
  `f_require_delivery_date` varchar(20) COLLATE utf8_unicode_ci DEFAULT NULL,
  `f_delivery_quantity` varchar(20) COLLATE utf8_unicode_ci DEFAULT NULL,
  `f_confirmed_quantity` varchar(20) COLLATE utf8_unicode_ci DEFAULT NULL,
  `f_oun` varchar(3) COLLATE utf8_unicode_ci DEFAULT NULL,
  `f_gr_date` varchar(20) COLLATE utf8_unicode_ci DEFAULT NULL,
  `f_storage_location` varchar(80) COLLATE utf8_unicode_ci DEFAULT NULL,
  `f_remark` varchar(132) COLLATE utf8_unicode_ci DEFAULT NULL,
  `f_poitemid` varchar(15) COLLATE utf8_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci