CREATE TABLE `srm_drawing_data_1` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `created_on` datetime DEFAULT NULL,
  `created_by` int(11) DEFAULT NULL,
  `private` int(11) DEFAULT '0',
  `active` tinyint(4) DEFAULT '1',
  `f_drawing_no_` varchar(20) COLLATE utf8_unicode_ci DEFAULT NULL,
  `f_drawing_description` varchar(40) COLLATE utf8_unicode_ci DEFAULT NULL,
  `f_drawing_type` varchar(128) COLLATE utf8_unicode_ci DEFAULT NULL,
  `f_usage` varchar(128) COLLATE utf8_unicode_ci DEFAULT NULL,
  `f_project_no_` varchar(20) COLLATE utf8_unicode_ci DEFAULT NULL,
  `f_valid_from` date DEFAULT NULL,
  `f_valid_to` date DEFAULT NULL,
  `f_company` int(11) DEFAULT NULL,
  `f_block_indicator` tinyint(4) DEFAULT NULL,
  `f_quote_indicator` varchar(2) COLLATE utf8_unicode_ci DEFAULT NULL,
  `f_remark` text COLLATE utf8_unicode_ci,
  `f_read_only_permission` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci