CREATE TABLE `srm_po_deliveryschedule_data_1` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `created_on` datetime DEFAULT NULL,
  `created_by` int(11) DEFAULT NULL,
  `private` int(11) DEFAULT '0',
  `active` tinyint(4) DEFAULT '1',
  `f_itembatch_no_` varchar(16) COLLATE utf8_unicode_ci DEFAULT NULL,
  `f_po_no_` varchar(16) COLLATE utf8_unicode_ci DEFAULT NULL,
  `f_item_no_` varchar(16) COLLATE utf8_unicode_ci DEFAULT NULL,
  `f_quantity` int(11) DEFAULT NULL,
  `f_oun` varchar(3) COLLATE utf8_unicode_ci DEFAULT NULL,
  `f_delivery_date` date DEFAULT NULL,
  `f_plant` varchar(40) COLLATE utf8_unicode_ci DEFAULT NULL,
  `f_storage_location` varchar(40) COLLATE utf8_unicode_ci DEFAULT NULL,
  `f_company` varchar(16) COLLATE utf8_unicode_ci DEFAULT NULL,
  `f_vendor` varchar(16) COLLATE utf8_unicode_ci DEFAULT NULL,
  `f_poid` varchar(15) COLLATE utf8_unicode_ci DEFAULT NULL,
  `f_poitemid` varchar(15) COLLATE utf8_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci